# Generated by Django 5.1.3 on 2024-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_rating_review'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(related_name='users_who_like_this_genre', to='books.genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_list',
            field=models.ManyToManyField(related_name='users_who_are_interested_in_this_book', to='books.book'),
        ),
    ]
