# Generated by Django 5.1.3 on 2024-12-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_default_country_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reading_list',
        ),
    ]
