# Generated by Django 5.1.3 on 2024-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('book_code', models.CharField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(max_length=254)),
                ('pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageLink', models.URLField(blank=True, max_length=1024, null=True)),
                ('genres', models.ManyToManyField(to='books.genre')),
            ],
        ),
    ]
