# Generated by Django 5.1.3 on 2024-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books_with_this_genre', to='books.genre'),
        ),
    ]
