# Generated by Django 5.1.3 on 2024-11-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_code',
            new_name='sku',
        ),
    ]
