# Generated by Django 5.1.3 on 2024-11-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_rating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
