# Generated by Django 5.1.3 on 2024-11-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_country_alter_book_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
