# Generated by Django 5.1.3 on 2024-11-30 14:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Book Image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
